project:
  type: website
  output-dir: _staff-site

website:
  title: "Scheduled Posts Example"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
