project:
  type: website
  output-dir: _site

website:
  title: "Scheduled Posts Example"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Posts

date-format: "X"
filters:
  - scheduled-posts
  - quarto
