project:
  type: website
  output-dir: _site-full

website:
  title: "Scheduled Posts Example (full render)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
