on:
  workflow_dispatch:
  push:
    branches: main
name: Publish Partial Site
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install dependencies
        run: |
          install.packages('yaml')
        shell: sudo Rscript {0}
      - name: Ignore future posts
        run: |
          Rscript ignore_future_docs.R
      - name: Render and Publish
        shell: bash
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          QUARTO_PROFILE: ignore-future
        run: |
          quarto publish netlify --id 5b76b005-6632-4125-9dbb-1a3d101a3b0c
